---
version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    # restore some of the defaults
    # (fill in the rest as needed)
    rules:
      - path: "internal/*"
        linters:
          - lll
