FROM cgr.dev/chainguard/static:latest
WORKDIR /
COPY spiffe-enable-ui .
# The Chainguard image has a single user 'nonroot' with uid '65532', belonging to gid '65532'.
USER nonroot

ENTRYPOINT ["/spiffe-enable-ui"]
