apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-enable-webhook
  namespace: cofide
spec:
  selector:
    matchLabels:
      app: spiffe-enable-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: spiffe-enable-webhook
    spec:
      containers:
      - name: spiffe-enable-webhook
        image: 010438484483.dkr.ecr.eu-west-1.amazonaws.com/cofide/spiffe-enable:v0.2.0-alpha
        imagePullPolicy: Always
        volumeMounts:
        - name: tls
          mountPath: "/tmp/k8s-webhook-server/serving-certs"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 10
      volumes:
        - name: tls
          secret:
            secretName: spiffe-enable-webhook-tls
            optional: false
