apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-injector-webhook
  namespace: cofide
spec:
  selector:
    matchLabels:
      app: sidecar-injector-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: sidecar-injector-webhook
    spec:
      containers:
      - name: sidecar-injector-webhook
        image: ko://github.com/cofide/injector-webhook
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: tls
          # the tls certificates automatically get mounted into the correct path
          mountPath: "/tmp/k8s-webhook-server/serving-certs"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 10
      volumes:
        - name: tls
          secret:
            # IMPORTANT: has to match from Certificate
            secretName: sidecar-injector-webhook-tls
            # the pod only gets created if the secret exists
            # so it waits until the cert-manager is done
            optional: false