apiVersion: v1
kind: Pod
metadata:
  name: awscli
  annotations:
    "spiffe.cofide.io/enabled": "true"
    #"cofide.io/aws-role-arn": "arn:aws:iam::590183795715:role/cofide-demo-oidc-discovery-provider-role"
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
