apiVersion: v1
kind: Service
metadata:
  name: spiffe-enable-webhook
  namespace: cofide
spec:
  ports:
    - name: https
      port: 9443
      protocol: TCP
  selector:
    app: spiffe-enable-webhook

