name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write
  packages: write

jobs:
    goreleaser:
      name: Build and Release with GoReleaser
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 # Required for GoReleaser to generate changelogs
  
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version-file: go.mod
            cache: true

        - uses: ko-build/setup-ko@v0.6

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
  
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            distribution: goreleaser
            version: '~> v2'
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
