name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
    goreleaser:
      name: Build and Release with GoReleaser
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 # Required for GoReleaser to generate changelogs
  
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version-file: go.mod
            cache: true

        - uses: ko-build/setup-ko@v0.6
  
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            distribution: goreleaser
            version: '~> v2'
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
