name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-push-images:
    name: Build and push images
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            repo: ghcr.io/cofide/spiffe-enable
            platform: linux/amd64
            runs-on: ubuntu-latest
            arch: amd64
          - dockerfile: Dockerfile
            repo: ghcr.io/cofide/spiffe-enable
            platform: linux/arm64
            runs-on: connect-ci-runner-arm
            arch: arm64
          - dockerfile: Dockerfile.nftables
            repo: ghcr.io/cofide/spiffe-enable-init
            platform: linux/amd64
            runs-on: ubuntu-latest
            arch: amd64
          - dockerfile: Dockerfile.nftables
            repo: ghcr.io/cofide/spiffe-enable-init
            platform: linux/arm64
            runs-on: connect-ci-runner-arm
            arch: arm64
          - dockerfile: Dockerfile.ui
            repo: ghcr.io/cofide/spiffe-enable-ui
            platform: linux/amd64
            runs-on: ubuntu-latest
            arch: amd64
          - dockerfile: Dockerfile.ui
            repo: ghcr.io/cofide/spiffe-enable-ui
            platform: linux/arm64
            runs-on: connect-ci-runner-arm
            arch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          provenance: false # this is a fix needed to be able to merge the images in a new manifest list later on
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{format('{0}:{1}-v0.1.2-test', matrix.repo, matrix.arch)}}

  build-merge-arch-images:
    runs-on: ubuntu-latest
    needs: build-push-images
    strategy:
      matrix:
        include:
          - repo: ghcr.io/cofide/spiffe-enable
          - repo: ghcr.io/cofide/spiffe-enable-init
          - repo: ghcr.io/cofide/spiffe-enable-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: pull images
        run: |
          docker pull --platform linux/amd64 ${{format('{0}:amd64-v0.2.1-test', matrix.repo)}}
          docker pull --platform linux/arm64 ${{format('{0}:arm64-v0.2.1-test', matrix.repo)}}
      - name: Merge images
        run: |
          docker manifest create $IMAGE --amend $IMAGE_AMD64 --amend $IMAGE_ARM64
          docker manifest annotate $IMAGE $IMAGE_AMD64 --os linux --arch amd64
          docker manifest annotate $IMAGE $IMAGE_ARM64  --os linux --arch arm64
          docker manifest push $IMAGE
        env:
          IMAGE_AMD64: ${{format('{0}:amd64-v0.2.1-test', matrix.repo)}}
          IMAGE_ARM64: ${{format('{0}:arm64-v0.2.1-test', matrix.repo)}}
          IMAGE: ${{format('{0}:v0.2.1-test', matrix.repo)}}
